#!/usr/bin/env bash
###############################################################################
#  IQCAP - Intelligent Quantum Chemistry Analysis Platform
#  Module: iqcap-report  (Automatic Result & Discussion Drafting via DeepSeek)
#
#  Version:    0.2.0
#  Author:     Hengyue Xu + AI assistant
#  Date:       2026-03-06
#  Copyright:  (C) 2024-2026 Hengyue Xu. All rights reserved.
#
#  Description:
#    Reads the AI-oriented summary generated by iqcap-summary.sh
#    (summary-ai.txt), sends it to the DeepSeek chat API with a strong
#    journal-writing prompt, and generates a detailed English
#    "Results and Discussion" draft in Markdown. The draft is instructed to
#    use paper-style Figure X placeholders whenever visual discussion would
#    naturally appear in a manuscript.
#
#  Usage:
#    # 1) Set your DeepSeek API key once in the shell (DO NOT hardcode it):
#    #    export DEEPSEEK_API_KEY="sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
#    #
#    # 2) From a system directory (e.g. xhy/C60-Li2S8):
#    #    bash /home/quantum/xhy/iqcap/bin/iqcap-report.sh
#    #
#    # 3) The script will write:
#    #    report/iqcap_result_discussion.md
#    #
#  Notes:
#    - This script never prints the API key; it only reads it from the
#      DEEPSEEK_API_KEY environment variable.
#    - The prompt is tailored for adsorption / host–guest / electronic
#      structure analysis and can be adjusted in the SYSTEM_PROMPT below.
###############################################################################

export DEEPSEEK_API_KEY="sk-561de935a9044d1cb866e83bf588a39c"

set -euo pipefail

IQCAP_NAME="IQCAP"
IQCAP_MODULE="iqcap-report"
IQCAP_VERSION="0.2.0"

###############################################################################
# Helpers
###############################################################################

die() {
  echo "[$IQCAP_MODULE] ERROR: $*" >&2
  exit 1
}

require_cmd() {
  local cmd="$1"
  command -v "$cmd" >/dev/null 2>&1 || die "Required command '$cmd' not found in PATH."
}

read_if_exists() {
  local path="$1"
  if [[ -f "$path" ]]; then
    echo "===== BEGIN FILE: $path ====="
    cat "$path"
    echo
    echo "===== END FILE: $path ====="
    echo
  fi
}

run_summary_if_needed() {
  local summary_script="/home/quantum/xhy/iqcap/bin/iqcap-summary.sh"
  local summary_txt="$PROJECT_ROOT/summary.txt"
  local summary_ai_txt="$PROJECT_ROOT/summary-ai.txt"

  if [[ -f "$summary_txt" && -f "$summary_ai_txt" ]]; then
    return
  fi

  [[ -x "$summary_script" || -f "$summary_script" ]] || \
    die "summary.txt or summary-ai.txt is missing, and iqcap-summary.sh was not found at $summary_script"

  echo "[$IQCAP_MODULE] summary.txt or summary-ai.txt not found. Running iqcap-summary.sh first..."
  bash "$summary_script"
}

truncate_to_bytes() {
  # Truncate stdin to at most N bytes (safe for UTF-8 because DeepSeek tolerates cut tails).
  local max_bytes="$1"
  python3 - "$max_bytes" <<'PY'
import sys

max_bytes = int(sys.argv[1])
data = sys.stdin.buffer.read(max_bytes)
sys.stdout.buffer.write(data)
PY
}

###############################################################################
# Pre-checks
###############################################################################

[[ -n "${DEEPSEEK_API_KEY:-}" ]] || die "DEEPSEEK_API_KEY not set. Please run:  export DEEPSEEK_API_KEY=\"sk-...\""

require_cmd python3

PROJECT_ROOT="$PWD"
BASE_NAME="$(basename "$PROJECT_ROOT")"
SUMMARY_TXT="$PROJECT_ROOT/summary.txt"
SUMMARY_AI_TXT="$PROJECT_ROOT/summary-ai.txt"

[[ -d "$PROJECT_ROOT/adsorption_energy" ]] || \
  echo "[$IQCAP_MODULE] WARNING: adsorption_energy/ not found under $PROJECT_ROOT; continuing anyway."

OUT_DIR="$PROJECT_ROOT/report"
mkdir -p "$OUT_DIR"
OUT_MD="$OUT_DIR/iqcap_result_discussion.md"
CONTEXT_TMP="$OUT_DIR/iqcap_report_context.tmp"

run_summary_if_needed

[[ -f "$SUMMARY_AI_TXT" ]] || die "Required file not found: $SUMMARY_AI_TXT"

echo "========================================"
echo " $IQCAP_NAME v$IQCAP_VERSION -- $IQCAP_MODULE"
echo " Project: $BASE_NAME"
echo " Root:    $PROJECT_ROOT"
echo " Output:  $OUT_MD"
echo " Prompt:  $SUMMARY_AI_TXT"
echo "========================================"

###############################################################################
# 1) Collect prompt-oriented context
###############################################################################

{
  echo "PROJECT_NAME: $BASE_NAME"
  echo
  echo "########################################"
  echo "# PRIMARY PROMPT PACKAGE (from iqcap-summary.sh)"
  echo "########################################"
  read_if_exists "$SUMMARY_AI_TXT"

  echo "########################################"
  echo "# COMPACT NUMERICAL SUMMARY"
  echo "########################################"
  read_if_exists "$SUMMARY_TXT"

} | truncate_to_bytes 131072 > "$CONTEXT_TMP"

###############################################################################
# 2) Build prompt and call DeepSeek API
###############################################################################

SYSTEM_PROMPT=$'You are a world-class native-English theoretical chemist, computational chemist, and physical chemist writing for a top-tier peer-reviewed journal.\n\
Your job is to convert a structured AI prompt package and supporting numerical summary into a publication-ready **Results and Discussion** section.\n\
\n\
GLOBAL REQUIREMENTS:\n\
- Write polished, detailed, high-level scientific prose in natural American English.\n\
- Sound like a human principal investigator, not an AI assistant.\n\
- Base the discussion ONLY on the provided evidence.\n\
- Preserve every reported numerical value exactly as given.\n\
- When evidence is qualitative or incomplete, write cautiously and avoid fabrication.\n\
- Integrate adsorption energetics, thermodynamics, charge transfer, global reactivity, bond orders, electrostatics, surface contacts, and weak-interaction analyses into one coherent narrative whenever justified by the data.\n\
- Make the text detailed enough to resemble a directly usable manuscript draft rather than a short summary.\n\
\n\
FIGURE STYLE REQUIREMENTS:\n\
- Write in a paper-like, figure-guided style.\n\
- When a discussion would naturally cite a visual result, refer to it as Figure X, Figure X(a), Figure X(b), Figure X(c), etc.\n\
- Use Figure X placeholders naturally for orbitals, ESP maps, Hirshfeld surfaces, contact plots, charge-redistribution figures, and weak-interaction plots.\n\
- If no visual details are explicitly supported by the text, keep the figure citation generic and do not invent spatial patterns.\n\
\n\
OUTPUT REQUIREMENTS:\n\
- Output only the final Results and Discussion text in Markdown.\n\
- Use informative subsection headings.\n\
- Do not include methods, bullet lists, or meta commentary.\n\
- Do not mention DeepSeek, prompts, or AI generation.\n'

USER_PROMPT_HEADER=$'Below is the prepared writing package for a single system.\n\
The PRIMARY PROMPT PACKAGE was generated from iqcap-summary.sh and already contains section-specific instructions plus local data blocks.\n\
Use it as the main basis for writing. The COMPACT NUMERICAL SUMMARY is supplemental.\n\
\n\
Write a detailed, journal-style Results and Discussion section that is as close as possible to a submission-ready manuscript draft, while remaining fully faithful to the supplied evidence.\n\
Where appropriate, use Figure X placeholders in the prose exactly as a paper would cite missing final figures.\n\
\n\
--- BEGIN ANALYSIS CONTEXT ---\n'

USER_PROMPT_FOOTER=$'\n--- END ANALYSIS CONTEXT ---\n'

USER_CONTENT="$(printf "%s\n%s\n%s" "$USER_PROMPT_HEADER" "$(cat "$CONTEXT_TMP")" "$USER_PROMPT_FOOTER")"

echo "[$IQCAP_MODULE] Contacting DeepSeek API..."

python3 - "$SYSTEM_PROMPT" "$USER_CONTENT" "$OUT_MD" <<'PYDS'
import sys
import json
import os
from pathlib import Path
from urllib import request

system_prompt = sys.argv[1]
user_content = sys.argv[2]
out_md = Path(sys.argv[3])

api_key = os.environ.get("DEEPSEEK_API_KEY")
if not api_key:
    raise SystemExit("DEEPSEEK_API_KEY not set in environment.")

url = "https://api.deepseek.com/chat/completions"
payload = {
    "model": "deepseek-chat",
    "messages": [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": user_content},
    ],
  "temperature": 0.2,
    "stream": False,
}
data = json.dumps(payload).encode("utf-8")
req = request.Request(url, data=data, method="POST")
req.add_header("Content-Type", "application/json")
req.add_header("Authorization", f"Bearer {api_key}")

try:
    with request.urlopen(req, timeout=120) as resp:
        resp_text = resp.read().decode("utf-8", errors="replace")
except Exception as e:
    raise SystemExit(f"DeepSeek API request failed: {e}")

try:
    obj = json.loads(resp_text)
    content = obj["choices"][0]["message"]["content"]
except Exception as e:
    raise SystemExit(f"Failed to parse DeepSeek response JSON: {e}\nRaw: {resp_text[:2000]}...")

out_md.parent.mkdir(parents=True, exist_ok=True)
out_md.write_text(content, encoding="utf-8")
print(f"[iqcap-report] Wrote report to: {out_md}")
PYDS

echo "[$IQCAP_MODULE] Done. Report saved to:"
echo "  $OUT_MD"

