#!/usr/bin/env bash
###############################################################################
#  IQCAP - Intelligent Quantum Chemistry Analysis Platform
#  Module: iqcap-2D_elect_figs  (2D Electronic Structure Visualization)
#
#  Version:    1.5.2
#  Author:     Hengyue Xu (ORCiD: 0000-0003-4438-9647)
#  Date:       2026-03-03
#  Copyright:  (C) 2024-2026 Hengyue Xu. All rights reserved.
#
#  Description:
#    Generates publication-quality 2D cross-section plots (color-filled contour
#    maps) from Gaussian .cub (cube) files.  Supports various electronic
#    structure properties: ELF, charge density difference (Δρ), electron
#    density, ESP, HOMO/LUMO orbitals, Fukui functions, IRI, IGMH, NCI, etc.
#
#    Two methods for defining the cutting plane:
#      Method 1  —  Three atoms (--plane-atoms "1,2,3")
#        Select three atom indices (1-based) from the cube file to define
#        a unique plane.  The plane passes through all three atoms.
#      Method 2  —  Plane specification:
#        a. Cartesian plane (--plane-cartesian xy/xz/yz)  with optional
#           --plane-offset (default: through molecular centre of mass).
#        b. Normal vector + point (--plane-normal "nx,ny,nz"
#           --plane-point "px,py,pz" in Ångström).
#        c. Automatic best-fit plane (--plane-auto)  through all atoms
#           via SVD decomposition — ideal for planar/near-planar molecules.
#
#  Prerequisite:
#    Cube files must already exist (generated by iqcap-basic_elect_analysis.sh
#    or iqcap-elect_interaction.sh).
#
#  External dependencies:
#    Python 3  - With packages: numpy, scipy, matplotlib
#
#  Usage:
#    bash iqcap-2D_elect_figs.sh --cube ELF.cub --plane-atoms "1,2,3"
#    bash iqcap-2D_elect_figs.sh --cube chgdiff.cub --plane-cartesian xz
#    bash iqcap-2D_elect_figs.sh --cube ELF.cub --plane-auto
#    bash iqcap-2D_elect_figs.sh --cube density.cub --plane-normal "0,1,0" \
#                                --plane-point "0,0.5,0"
#    bash iqcap-2D_elect_figs.sh --cube ELF.cub --list-atoms
#
###############################################################################

set -euo pipefail

IQCAP_NAME="IQCAP"
IQCAP_FULLNAME="Intelligent Quantum Chemistry Analysis Platform"
IQCAP_MODULE="iqcap-2D_elect_figs"
IQCAP_VERSION="1.5.2"
IQCAP_AUTHOR="Hengyue Xu (ORCiD: 0000-0003-4438-9647)"
IQCAP_COPYRIGHT="(C) 2024-2026 Hengyue Xu. All rights reserved."

###############################################################################
# User configuration
###############################################################################
CUBE_FILE=""
OUTPUT_DIR=""
OUTPUT_NAME=""

# Plane definition
PLANE_METHOD=""
PLANE_ATOMS=""
PLANE_CARTESIAN=""
PLANE_OFFSET="auto"
PLANE_NORMAL=""
PLANE_POINT=""

# Property type (for colormap / title)
PROPERTY_TYPE="auto"

# Plot parameters
CMAP=""
VMIN=""
VMAX=""
EXTENSION=3.0
RESOLUTION=300
DPI=300
CONTOUR_LEVELS=20
SHOW_ATOMS=1
SHOW_BONDS=1
SHOW_LABELS=1
FIGSIZE="8,7"

# Publication-style preset (optional)
#   --type 1: portrait (竖着风格)
#   --type 2: landscape (横着风格)
PLOT_TYPE=""

# In-plane rotation of the slice (degrees, clockwise when viewing along +plane normal)
PLANE_ROTAT="0"

# Utility flags
LIST_ATOMS=0

###############################################################################
# CLI
###############################################################################
while [[ $# -gt 0 ]]; do
  case "$1" in
    --cube)             CUBE_FILE="$2";                                    shift 2 ;;
    --output-dir)       OUTPUT_DIR="$2";                                   shift 2 ;;
    --output-name)      OUTPUT_NAME="$2";                                  shift 2 ;;
    --type)             PLOT_TYPE="$2";                                    shift 2 ;;
    --plane-atoms)      PLANE_METHOD="atoms";     PLANE_ATOMS="$2";        shift 2 ;;
    --plane-cartesian)  PLANE_METHOD="cartesian";  PLANE_CARTESIAN="$2";   shift 2 ;;
    --plane-offset)     PLANE_OFFSET="$2";                                 shift 2 ;;
    --plane-normal)     PLANE_METHOD="normal";    PLANE_NORMAL="$2";       shift 2 ;;
    --plane-point)      PLANE_POINT="$2";                                  shift 2 ;;
    --plane-auto)       PLANE_METHOD="auto";                               shift 1 ;;
    --property)         PROPERTY_TYPE="$2";                                shift 2 ;;
    --cmap)             CMAP="$2";                                         shift 2 ;;
    --vmin)             VMIN="$2";                                         shift 2 ;;
    --vmax)             VMAX="$2";                                         shift 2 ;;
    --extension)        EXTENSION="$2";                                    shift 2 ;;
    --resolution)       RESOLUTION="$2";                                   shift 2 ;;
    --dpi)              DPI="$2";                                          shift 2 ;;
    --contour-levels)   CONTOUR_LEVELS="$2";                               shift 2 ;;
    --no-atoms)         SHOW_ATOMS=0;                                      shift 1 ;;
    --no-bonds)         SHOW_BONDS=0;                                      shift 1 ;;
    --no-labels)        SHOW_LABELS=0;                                     shift 1 ;;
    --figsize)          FIGSIZE="$2";                                      shift 2 ;;
    --rotat)            PLANE_ROTAT="$2";                                  shift 2 ;;
    --list-atoms)       LIST_ATOMS=1;                                      shift 1 ;;
    -h|--help)
      cat <<EOF

$IQCAP_NAME v$IQCAP_VERSION  —  $IQCAP_MODULE
$IQCAP_FULLNAME
$IQCAP_COPYRIGHT

Generate 2D cross-section plots from Gaussian cube files.

Usage:
  bash $IQCAP_MODULE.sh --cube <file.cub> <plane-method> [options]

Required:
  --cube FILE              Path to a Gaussian .cub file

Plane definition (choose one):
  --plane-atoms "i,j,k"    Define plane through 3 atoms (1-based indices)
  --plane-cartesian PLANE   Cartesian plane: xy, xz, or yz
    --plane-offset FLOAT      Offset in Å along the perpendicular axis
                              (default: auto — through centre of mass)
  --plane-normal "nx,ny,nz" Plane normal vector (arbitrary units, auto-normalised)
    --plane-point "x,y,z"     A point on the plane (Å)
  --plane-auto              Best-fit molecular plane via SVD

Utility:
  --list-atoms              List atoms and coordinates from the cube file, then exit

Property type:
  --property TYPE           Override auto-detection. Types:
                            elf, chgdiff, density, esp, homo, lumo, fukui,
                            iri, igmh, nci, custom

Plot options:
  --cmap NAME               Matplotlib colormap (default: auto per property)
  --vmin FLOAT              Colour scale minimum (default: auto)
  --vmax FLOAT              Colour scale maximum (default: auto)
  --extension FLOAT         Å extension beyond atoms (default: 3.0)
  --resolution INT          Grid points per axis (default: 300)
  --dpi INT                 Image DPI (default: 300)
  --contour-levels INT      Number of contour lines (default: 20)
  --no-atoms                Hide atom markers
  --no-bonds                Hide bond lines
  --no-labels               Hide atom labels
  --type TYPE              Publication layout preset:
                            1 = portrait (竖着风格, colorbar on the right)
                            2 = landscape (横着风格, colorbar below the map)
                            If set, overrides --figsize and normalizes aspect ratio.
  --rotat DEG              Rotate the cutting-plane axes clockwise by DEG degrees
                            (viewing along the +normal direction). Only the u–v map
                            rotates; titles, colorbar, and margins follow --type.
  --figsize "W,H"           Figure size in inches (default: "8,7")

Output:
  --output-dir DIR          Output directory (default: same as cube file)
  --output-name NAME        Output filename stem (default: <cube>_2d)

Info:
  -h, --help                Show this help message
  -V, --version             Show version information

Examples:
  bash $IQCAP_MODULE.sh --cube ELF.cub --plane-atoms "1,2,3"
  bash $IQCAP_MODULE.sh --cube chgdiff.cub --plane-cartesian xz --plane-offset 0.38
  bash $IQCAP_MODULE.sh --cube ELF.cub --plane-auto --vmin 0 --vmax 1
  bash $IQCAP_MODULE.sh --cube density.cub --plane-normal "0,0,1" --plane-point "0,0,0.4"
  bash $IQCAP_MODULE.sh --cube ELF.cub --list-atoms

EOF
      exit 0
      ;;
    -V|--version)
      echo "$IQCAP_NAME $IQCAP_VERSION ($IQCAP_MODULE)"
      exit 0
      ;;
    *) echo "Unknown argument: $1" >&2; exit 1 ;;
  esac
done

###############################################################################
# Validation
###############################################################################
[[ -n "$CUBE_FILE" ]] || {
  echo "ERROR: --cube is required. Use --help for usage." >&2; exit 1
}
[[ -f "$CUBE_FILE" ]] || {
  echo "ERROR: Cube file not found: $CUBE_FILE" >&2; exit 1
}
CUBE_FILE="$(cd "$(dirname "$CUBE_FILE")" && pwd)/$(basename "$CUBE_FILE")"

if [[ "$LIST_ATOMS" -eq 0 ]]; then
  [[ -n "$PLANE_METHOD" ]] || {
    echo "ERROR: Plane method required. Use --plane-atoms, --plane-cartesian, --plane-normal, or --plane-auto." >&2
    exit 1
  }
fi

python3 -c "import numpy"     >/dev/null 2>&1 || { echo "ERROR: Python numpy required.  pip install numpy"      >&2; exit 1; }
python3 -c "import scipy"     >/dev/null 2>&1 || { echo "ERROR: Python scipy required.  pip install scipy"      >&2; exit 1; }
python3 -c "import matplotlib" >/dev/null 2>&1 || { echo "ERROR: Python matplotlib required.  pip install matplotlib" >&2; exit 1; }

if [[ -z "$OUTPUT_DIR" ]]; then
  OUTPUT_DIR="$(dirname "$CUBE_FILE")"
fi
mkdir -p "$OUTPUT_DIR"
OUTPUT_DIR="$(cd "$OUTPUT_DIR" && pwd)"

if [[ -z "$OUTPUT_NAME" ]]; then
  OUTPUT_NAME="$(basename "$CUBE_FILE" .cub)_2d"
fi

# Apply publication layout preset (optional)
if [[ -n "$PLOT_TYPE" ]]; then
  case "$PLOT_TYPE" in
    1)
      # Portrait: standardize to a 1924x2064 target frame.
      FIGSIZE="6.52,7.00"
      ;;
    2)
      # Landscape: standardize to a 2298x1768 target frame.
      FIGSIZE="7.80,6.00"
      ;;
    *)
      echo "ERROR: Invalid --type value: $PLOT_TYPE (expected 1 or 2)" >&2
      exit 1
      ;;
  esac
fi

###############################################################################
# Banner
###############################################################################
echo "========================================"
echo " $IQCAP_NAME v$IQCAP_VERSION"
echo " $IQCAP_FULLNAME"
echo " Module: $IQCAP_MODULE (2D Electronic Structure Visualization)"
echo "========================================"
echo "  Cube file:  $CUBE_FILE"
if [[ "$LIST_ATOMS" -eq 1 ]]; then
  echo "  Mode:       --list-atoms"
else
  echo "  Output:     $OUTPUT_DIR/${OUTPUT_NAME}.png"
  echo "  Plane:      $PLANE_METHOD"
  echo "  Property:   $PROPERTY_TYPE"
  [[ "$PLANE_ROTAT" != "0" ]] && echo "  Rotation:   ${PLANE_ROTAT}° (clockwise in plane)"
  [[ -n "$PLOT_TYPE" ]] && echo "  Layout:     type $PLOT_TYPE"
fi
echo "========================================"

###############################################################################
# Main Python script
###############################################################################
python3 - \
  "$CUBE_FILE" "$OUTPUT_DIR" "$OUTPUT_NAME" \
  "$PLANE_METHOD" "$PLANE_ATOMS" "$PLANE_CARTESIAN" "$PLANE_OFFSET" \
  "$PLANE_NORMAL" "$PLANE_POINT" \
  "$PROPERTY_TYPE" "$CMAP" "$VMIN" "$VMAX" \
  "$EXTENSION" "$RESOLUTION" "$DPI" "$CONTOUR_LEVELS" \
  "$SHOW_ATOMS" "$SHOW_BONDS" "$SHOW_LABELS" "$FIGSIZE" \
  "$LIST_ATOMS" "$PLOT_TYPE" "$PLANE_ROTAT" \
  <<'PYPLOT2D'
import sys
import math
import numpy as np
from pathlib import Path
from PIL import Image

BOHR2ANG = 0.529177249

ELEMENT_SYM = {
    1:'H',2:'He',3:'Li',4:'Be',5:'B',6:'C',7:'N',8:'O',9:'F',10:'Ne',
    11:'Na',12:'Mg',13:'Al',14:'Si',15:'P',16:'S',17:'Cl',18:'Ar',
    19:'K',20:'Ca',21:'Sc',22:'Ti',23:'V',24:'Cr',25:'Mn',26:'Fe',
    27:'Co',28:'Ni',29:'Cu',30:'Zn',31:'Ga',32:'Ge',33:'As',34:'Se',
    35:'Br',36:'Kr',46:'Pd',47:'Ag',53:'I',78:'Pt',79:'Au',
}

COVALENT_R = {
    'H':0.31,'He':0.28,'Li':1.28,'Be':0.96,'B':0.84,'C':0.76,'N':0.71,
    'O':0.66,'F':0.57,'Ne':0.58,'Na':1.66,'Mg':1.41,'Al':1.21,'Si':1.11,
    'P':1.07,'S':1.05,'Cl':1.02,'Ar':1.06,'K':2.03,'Ca':1.76,'Ti':1.60,
    'Cr':1.39,'Mn':1.39,'Fe':1.32,'Co':1.26,'Ni':1.24,'Cu':1.32,'Zn':1.22,
    'Br':1.20,'I':1.39,'Pd':1.39,'Pt':1.36,'Au':1.36,
}

ATOM_COLORS = {
    'H':'#FFFFFF','Li':'#90EE90','Na':'#FFAEB9','B':'#FFAEB9','C':'#8E8E8E','N':'#3050F8','O':'#FF0D0D','F':'#1cffe8',
    'Cl':'#1FF01F','Br':'#A62929','S':'#FFFF30','P':'#FF8000','Si':'#F0C8A0',
    'K':'#8F40D4','Ca':'#3DFF00','Fe':'#E06633','Cu':'#C88033',
    'Zn':'#7D80B0','I':'#940094','Au':'#FFD123','Pt':'#D0D0E0',
}

ATOM_DRAW_R = {
    'H':0.12,'C':0.22,'N':0.20,'O':0.19,'F':0.16,'Cl':0.22,
    'Br':0.24,'S':0.24,'P':0.22,'Si':0.24,'Fe':0.26,'Cu':0.24,
}

import os, re
spec = os.environ.get("IQCAP_ELEMENT_COLORS", "").strip()
if spec:
    for tok in re.split(r'[,;]\s*', spec):
        if not tok or '=' not in tok:
            continue
        el, val = tok.split('=', 1)
        el = el.strip()
        val = val.strip()
        if re.fullmatch(r'#[0-9A-Fa-f]{6}', val):
            ATOM_COLORS[el] = val

# ---------------------------------------------------------------------------
# Parse arguments
# ---------------------------------------------------------------------------
args = sys.argv[1:]
(cube_path, out_dir, out_name,
 plane_method, plane_atoms_s, plane_cart_s, plane_offset_s,
 plane_normal_s, plane_point_s,
 prop_type, cmap_name, vmin_s, vmax_s,
 ext_s, res_s, dpi_s, nlev_s,
 show_at_s, show_bd_s, show_lb_s, figsize_s,
 list_atoms_s, type_s, rotat_s) = args

extension  = float(ext_s)
resolution = int(res_s)
dpi        = int(dpi_s)
n_levels   = int(nlev_s)
show_atoms = show_at_s == "1"
show_bonds = show_bd_s == "1"
show_labels = show_lb_s == "1"
list_atoms_only = list_atoms_s == "1"
figw, figh = [float(v) for v in figsize_s.split(",")]

# ---------------------------------------------------------------------------
# Cube file parser
# ---------------------------------------------------------------------------
def parse_cube(filepath):
    with open(filepath, 'r') as fh:
        lines = fh.readlines()

    parts3 = lines[2].split()
    natoms = abs(int(parts3[0]))
    origin = np.array([float(parts3[1]), float(parts3[2]), float(parts3[3])])

    nv = []
    axes = []
    for k in range(3):
        p = lines[3 + k].split()
        nv.append(int(p[0]))
        axes.append(np.array([float(p[1]), float(p[2]), float(p[3])]))

    atoms = []
    for k in range(natoms):
        p = lines[6 + k].split()
        anum = int(p[0])
        pos = np.array([float(p[2]), float(p[3]), float(p[4])])
        atoms.append((anum, pos))

    vals = []
    for line in lines[6 + natoms:]:
        vals.extend(float(v) for v in line.split())
    data = np.array(vals).reshape(nv[0], nv[1], nv[2])

    return origin, nv, axes, atoms, data

origin_bohr, nv, axes_bohr, atoms_bohr, data = parse_cube(cube_path)

origin_ang = origin_bohr * BOHR2ANG
axes_ang   = [a * BOHR2ANG for a in axes_bohr]
atoms_ang  = [(n, p * BOHR2ANG) for n, p in atoms_bohr]

# ---------------------------------------------------------------------------
# --list-atoms mode
# ---------------------------------------------------------------------------
if list_atoms_only:
    print(f"\n  Atoms in {Path(cube_path).name}  ({len(atoms_ang)} atoms):")
    print(f"  {'Idx':>4s}  {'Elem':>4s}  {'X (Å)':>10s}  {'Y (Å)':>10s}  {'Z (Å)':>10s}")
    print("  " + "-" * 46)
    for i, (num, pos) in enumerate(atoms_ang):
        sym = ELEMENT_SYM.get(num, f"Z{num}")
        print(f"  {i+1:4d}  {sym:>4s}  {pos[0]:10.5f}  {pos[1]:10.5f}  {pos[2]:10.5f}")
    print()
    sys.exit(0)

# ---------------------------------------------------------------------------
# Plane definition helpers
# ---------------------------------------------------------------------------
all_pos = np.array([p for _, p in atoms_ang])
com = all_pos.mean(axis=0)

def plane_from_3atoms(idx_str):
    indices = [int(i) for i in idx_str.split(",")]
    if len(indices) != 3:
        raise SystemExit("ERROR: --plane-atoms requires exactly 3 comma-separated indices.")
    for ix in indices:
        if ix < 1 or ix > len(atoms_ang):
            raise SystemExit(f"ERROR: Atom index {ix} out of range [1, {len(atoms_ang)}].")
    pts = [atoms_ang[i - 1][1] for i in indices]
    v1 = pts[1] - pts[0]
    v2 = pts[2] - pts[0]
    normal = np.cross(v1, v2)
    norm_len = np.linalg.norm(normal)
    if norm_len < 1e-10:
        raise SystemExit("ERROR: The 3 atoms are collinear — cannot define a unique plane.\n"
                         "  Tip: choose atoms that are not on the same line, or use --plane-cartesian / --plane-auto.")
    normal /= norm_len
    center = (pts[0] + pts[1] + pts[2]) / 3.0
    return normal, center

def plane_cartesian(name, offset_s):
    name = name.lower()
    if offset_s == "auto":
        off_val = None
    else:
        off_val = float(offset_s)
    if name == "xy":
        normal = np.array([0., 0., 1.])
        pt = np.array([com[0], com[1], com[2] if off_val is None else off_val])
    elif name == "xz":
        normal = np.array([0., 1., 0.])
        pt = np.array([com[0], com[1] if off_val is None else off_val, com[2]])
    elif name == "yz":
        normal = np.array([1., 0., 0.])
        pt = np.array([com[0] if off_val is None else off_val, com[1], com[2]])
    else:
        raise SystemExit(f"ERROR: Unknown Cartesian plane '{name}'. Use xy, xz, or yz.")
    return normal, pt

def plane_normal_point(norm_s, pt_s):
    if not norm_s:
        raise SystemExit("ERROR: --plane-normal requires a value, e.g. '0,1,0'.")
    if not pt_s:
        raise SystemExit("ERROR: --plane-point is required with --plane-normal.")
    n = np.array([float(v) for v in norm_s.split(",")])
    nl = np.linalg.norm(n)
    if nl < 1e-12:
        raise SystemExit("ERROR: Normal vector must be non-zero.")
    n /= nl
    pt = np.array([float(v) for v in pt_s.split(",")])
    return n, pt

def plane_auto():
    centered = all_pos - com
    if len(atoms_ang) < 3:
        print("  WARNING: < 3 atoms — using XZ plane through centre of mass.")
        return np.array([0., 1., 0.]), com.copy()
    _, s, vh = np.linalg.svd(centered)
    normal = vh[-1]
    if s[-1] / (s[0] + 1e-30) > 0.3:
        print("  NOTE: Molecule is not planar; SVD-plane is the best-fit plane.")
    return normal, com.copy()

# Determine plane
if plane_method == "atoms":
    normal, center = plane_from_3atoms(plane_atoms_s)
elif plane_method == "cartesian":
    normal, center = plane_cartesian(plane_cart_s, plane_offset_s)
elif plane_method == "normal":
    normal, center = plane_normal_point(plane_normal_s, plane_point_s)
elif plane_method == "auto":
    normal, center = plane_auto()
else:
    raise SystemExit(f"ERROR: Unknown plane method '{plane_method}'.")

# Ensure consistent normal direction (positive z-component preferred)
if normal[2] < 0:
    normal = -normal

# ---------------------------------------------------------------------------
# Build orthonormal basis on the plane
# ---------------------------------------------------------------------------
def build_basis(n):
    ref = np.array([1., 0., 0.]) if abs(n[0]) < 0.9 else np.array([0., 1., 0.])
    e1 = np.cross(n, ref)
    e1 /= np.linalg.norm(e1)
    e2 = np.cross(n, e1)
    e2 /= np.linalg.norm(e2)
    return e1, e2

e1, e2 = build_basis(normal)

# Optional in-plane rotation (clockwise in the plot when viewing along +normal)
rot_deg = float(rotat_s) if (rotat_s and str(rotat_s).strip()) else 0.0
if abs(rot_deg) > 1e-12:
    th = math.radians(rot_deg)
    co, si = math.cos(th), math.sin(th)
    # e1' = cos(th)*e1 + sin(th)*e2 ; e2' = -sin(th)*e1 + cos(th)*e2  (basis rotates CW)
    e1, e2 = co * e1 + si * e2, -si * e1 + co * e2

# ---------------------------------------------------------------------------
# Determine 2D extent from projected atoms
# ---------------------------------------------------------------------------
proj_u = np.dot(all_pos - center, e1)
proj_v = np.dot(all_pos - center, e2)
u_lo, u_hi = proj_u.min() - extension, proj_u.max() + extension
v_lo, v_hi = proj_v.min() - extension, proj_v.max() + extension

# ---------------------------------------------------------------------------
# Extract 2D slice via interpolation
# ---------------------------------------------------------------------------
from scipy.ndimage import map_coordinates

axis_mat = np.array(axes_ang)
try:
    axis_inv = np.linalg.inv(axis_mat)
except np.linalg.LinAlgError:
    raise SystemExit("ERROR: Cube file axis vectors are singular — cannot invert.")

u_grid = np.linspace(u_lo, u_hi, resolution)
v_grid = np.linspace(v_lo, v_hi, resolution)
uu, vv = np.meshgrid(u_grid, v_grid, indexing='ij')

pts3d = (center[np.newaxis, np.newaxis, :]
         + uu[:, :, np.newaxis] * e1
         + vv[:, :, np.newaxis] * e2)
pts_flat = pts3d.reshape(-1, 3)

frac = (axis_inv @ (pts_flat - origin_ang).T)   # shape (3, N)

values_2d = map_coordinates(data, frac, order=1, mode='constant', cval=0.0)
values_2d = values_2d.reshape(resolution, resolution)

# ---------------------------------------------------------------------------
# Auto-detect property type from filename
# ---------------------------------------------------------------------------
cube_stem = Path(cube_path).stem.lower()

if prop_type == "auto":
    if "elf" in cube_stem:
        prop_type = "elf"
    elif "chgdiff" in cube_stem or "diff" in cube_stem:
        prop_type = "chgdiff"
    elif "esp" in cube_stem:
        prop_type = "esp"
    elif "homo" in cube_stem:
        prop_type = "homo"
    elif "lumo" in cube_stem:
        prop_type = "lumo"
    elif cube_stem.startswith("f0") or cube_stem.startswith("f+") or cube_stem.startswith("f-") \
         or "fukui" in cube_stem or cube_stem == "dd":
        prop_type = "fukui"
    elif cube_stem == "func1":
        prop_type = "signlambda2rho"
    elif "iri" in cube_stem or cube_stem == "func2":
        prop_type = "iri"
    elif "dg_inter" in cube_stem or "dg_intra" in cube_stem:
        prop_type = "igmh"
    elif "sl2r" in cube_stem:
        prop_type = "signlambda2rho"
    elif "density" in cube_stem:
        prop_type = "density"
    else:
        prop_type = "custom"

PROP_DEFAULTS = {
    "elf":             {"cmap": "RdYlBu_r", "vmin": 0.0,  "vmax": 1.0,
                        "title": "Electron Localization Function (ELF)", "sym": False},
    "chgdiff":         {"cmap": "bwr",       "vmin": None, "vmax": None,
                        "title": "Charge Density Difference Δρ",        "sym": True},
    "esp":             {"cmap": "RdBu_r",    "vmin": None, "vmax": None,
                        "title": "Electrostatic Potential (ESP)",       "sym": True},
    "homo":            {"cmap": "RdBu_r",    "vmin": None, "vmax": None,
                        "title": "HOMO",                               "sym": True},
    "lumo":            {"cmap": "RdBu_r",    "vmin": None, "vmax": None,
                        "title": "LUMO",                               "sym": True},
    "fukui":           {"cmap": "RdBu_r",    "vmin": None, "vmax": None,
                        "title": "Fukui Function",                     "sym": True},
    "density":         {"cmap": "YlGnBu",    "vmin": 0.0,  "vmax": None,
                        "title": "Electron Density ρ",                 "sym": False},
    "iri":             {"cmap": "viridis",    "vmin": 0.0,  "vmax": None,
                        "title": "Interaction Region Indicator (IRI)",  "sym": False},
    "signlambda2rho":  {"cmap": "bwr",        "vmin": None, "vmax": None,
                        "title": "sign(λ₂)ρ",                         "sym": True},
    "igmh":            {"cmap": "viridis",    "vmin": 0.0,  "vmax": None,
                        "title": "IGMH δg",                           "sym": False},
    "custom":          {"cmap": "viridis",    "vmin": None, "vmax": None,
                        "title": cube_stem,                            "sym": False},
}

defs = PROP_DEFAULTS.get(prop_type, PROP_DEFAULTS["custom"])
use_cmap = cmap_name if cmap_name else defs["cmap"]

nonzero = values_2d[np.abs(values_2d) > 1e-30]
if len(nonzero) > 0:
    pct99 = float(np.percentile(np.abs(nonzero), 99))
else:
    pct99 = 1.0

if vmin_s:
    use_vmin = float(vmin_s)
elif defs["vmin"] is not None:
    use_vmin = defs["vmin"]
elif defs["sym"]:
    use_vmin = -pct99
else:
    use_vmin = float(np.percentile(nonzero, 1)) if len(nonzero) else 0.0

if vmax_s:
    use_vmax = float(vmax_s)
elif defs["vmax"] is not None:
    use_vmax = defs["vmax"]
elif defs["sym"]:
    use_vmax = pct99
else:
    use_vmax = float(np.percentile(nonzero, 99)) if len(nonzero) else 1.0

if abs(use_vmax - use_vmin) < 1e-30:
    use_vmin, use_vmax = use_vmin - 0.5, use_vmax + 0.5

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
print(f"  Plane normal:   ({normal[0]:.4f}, {normal[1]:.4f}, {normal[2]:.4f})")
print(f"  Plane centre:   ({center[0]:.4f}, {center[1]:.4f}, {center[2]:.4f}) Å")
print(f"  Plot extent:    u=[{u_lo:.2f}, {u_hi:.2f}]  v=[{v_lo:.2f}, {v_hi:.2f}] Å")
if abs(rot_deg) > 1e-12:
    print(f"  Plane rotation: {rot_deg:g}° clockwise (view along +normal)")
print(f"  Property type:  {prop_type}")
print(f"  Colormap:       {use_cmap}  [{use_vmin:.4g}, {use_vmax:.4g}]")
print(f"  Resolution:     {resolution}×{resolution}  DPI={dpi}")

# ---------------------------------------------------------------------------
# Matplotlib plotting
# ---------------------------------------------------------------------------
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from matplotlib.patches import Circle
from matplotlib.ticker import FormatStrFormatter

plt.rcParams.update({
    'font.family': 'DejaVu Sans',
    'mathtext.fontset': 'dejavusans',
    'axes.linewidth': 1.2,
})

fig, ax = plt.subplots(1, 1, figsize=(figw, figh))

fill_levels = np.linspace(use_vmin, use_vmax, max(n_levels * 5, 100))
cf = ax.contourf(u_grid, v_grid, values_2d.T,
                 levels=fill_levels, cmap=use_cmap, extend='both')

cl_levels = np.linspace(use_vmin, use_vmax, n_levels + 2)[1:-1]
ax.contour(u_grid, v_grid, values_2d.T,
           levels=cl_levels, colors='k', linewidths=0.3, alpha=0.4)

from mpl_toolkits.axes_grid1 import make_axes_locatable
if type_s == "2":
    cbar = fig.colorbar(cf, ax=ax, orientation="horizontal", pad=0.14,
                        shrink=0.88, aspect=28)
    cbar.set_label(defs["title"], fontsize=15, labelpad=10)
    cbar.ax.tick_params(labelsize=15)
else:
    divider = make_axes_locatable(ax)
    cax = divider.append_axes("right", size="3%", pad=0.08)
    cbar = fig.colorbar(cf, cax=cax)
    cbar.set_label(defs["title"], fontsize=15, labelpad=10)
    cbar.ax.tick_params(labelsize=15)

if type_s == "2":
    cbar.ax.xaxis.set_major_formatter(FormatStrFormatter("%.2f"))
else:
    cbar.ax.yaxis.set_major_formatter(FormatStrFormatter("%.2f"))

# --- Atom / bond overlay ---------------------------------------------------
if show_atoms or show_bonds:
    atom_proj = []
    atom_dist = []
    for i, (num, pos) in enumerate(atoms_ang):
        u_p = float(np.dot(pos - center, e1))
        v_p = float(np.dot(pos - center, e2))
        d   = float(abs(np.dot(pos - center, normal)))
        sym = ELEMENT_SYM.get(num, f"Z{num}")
        atom_proj.append((i, sym, u_p, v_p, d))
        atom_dist.append(d)

    max_vis_dist = 2.0

    if show_bonds:
        for ia in range(len(atoms_ang)):
            for ib in range(ia + 1, len(atoms_ang)):
                n1, p1 = atoms_ang[ia]
                n2, p2 = atoms_ang[ib]
                s1 = ELEMENT_SYM.get(n1, '?')
                s2 = ELEMENT_SYM.get(n2, '?')
                dist_3d = float(np.linalg.norm(p2 - p1))
                r1 = COVALENT_R.get(s1, 1.5)
                r2 = COVALENT_R.get(s2, 1.5)
                cov_cut = (r1 + r2) * 1.3

                is_hbond = False
                hb_cut = 2.5
                if s1 == 'H' and s2 in ('N', 'O', 'F', 'Cl'):
                    is_hbond = dist_3d > cov_cut and dist_3d < hb_cut
                elif s2 == 'H' and s1 in ('N', 'O', 'F', 'Cl'):
                    is_hbond = dist_3d > cov_cut and dist_3d < hb_cut

                draw = dist_3d < cov_cut or is_hbond
                if not draw:
                    continue

                _, _, u1, v1, d1 = atom_proj[ia]
                _, _, u2, v2, d2 = atom_proj[ib]
                avg_d = (d1 + d2) / 2.0
                if avg_d > max_vis_dist:
                    continue
                alpha = max(0.2, 1.0 - avg_d * 0.4)
                ls = '--' if is_hbond else '-'
                lw = 1.0 if is_hbond else 1.8
                ax.plot([u1, u2], [v1, v2], color='#333333',
                        linestyle=ls, linewidth=lw, alpha=alpha, zorder=8)

    if show_atoms:
        for idx, sym, u_p, v_p, d in atom_proj:
            if d > max_vis_dist:
                continue
            alpha = max(0.3, 1.0 - d * 0.4)
            fc = ATOM_COLORS.get(sym, '#AAAAAA')
            r  = ATOM_DRAW_R.get(sym, 0.20) * (1.0 - 0.15 * min(d, 2.0))
            circ = Circle((u_p, v_p), r,
                           facecolor=fc, edgecolor='black',
                           linewidth=1.3, alpha=alpha, zorder=10)
            ax.add_patch(circ)
            if show_labels:
                ax.annotate(f"{sym}{idx+1}", (u_p, v_p),
                            textcoords="offset points", xytext=(5, 5),
                            fontsize=8, fontweight='bold', color='black',
                            alpha=alpha, zorder=11)

ax.set_xlabel('u (Å)', fontsize=15)
ax.set_ylabel('v (Å)', fontsize=15)
ax.set_title(f"{defs['title']}  —  2D Cross-Section", fontsize=13, fontweight='bold', pad=10)
ax.set_aspect('equal')
ax.tick_params(labelsize=15)

plt.tight_layout()
out_path = Path(out_dir) / f"{out_name}.png"
fig.savefig(str(out_path), dpi=dpi, bbox_inches='tight', facecolor='white')
plt.close()

# Optional publication normalization:
# - Keep aspect ratio standardized per --type (no stretch; white padding).
if type_s in ("1", "2"):
    target_frames = {
        "1": (1924, 2064),  # portrait (竖着风格)
        "2": (2298, 1768),  # landscape (横着风格)
    }
    tw, th = target_frames[type_s]

    # Letterbox:等比缩放 + 白底居中（避免拉伸变形）。
    img = Image.open(str(out_path)).convert("RGBA")
    iw, ih = img.size
    scale = min(tw / iw, th / ih)
    nw, nh = int(round(iw * scale)), int(round(ih * scale))

    resized = img.resize((nw, nh), Image.Resampling.LANCZOS)
    canvas = Image.new("RGBA", (tw, th), (255, 255, 255, 255))
    x = (tw - nw) // 2
    y = (th - nh) // 2
    canvas.paste(resized, (x, y), resized)
    canvas.convert("RGB").save(str(out_path), format="PNG")

    print(f"  Normalized (type {type_s}): {tw}x{th}")

print(f"\n  Saved: {out_path}")
PYPLOT2D

echo ""
echo "========================================"
echo " Done."
echo "========================================"
