#!/usr/bin/env bash
###############################################################################
#  IQCAP - Intelligent Quantum Chemistry Analysis Platform
#  Module: iqcap-sp-CPCM  (Single-Point with CPCM Solvent)
#
#  Version:    1.0.0
#  Author:     Hengyue Xu (ORCiD: 0000-0003-4438-9647)
#  Date:       2026-06-28
#  Copyright:  (C) 2024-2026 Hengyue Xu. All rights reserved.
#
#  Description:
#    Zero-argument CPCM(Water) single-point on an existing optimization.
#    Run from any directory containing an orca-opt.sh optimization/ output.
#    Auto-discovers: theory level (from iqcap_orca.env), charge/multiplicity
#    (from sp.inp / opt.inp), and geometry (optimization/opt.xyz).
#
#  Usage:
#    cd <any orca-opt.sh output dir containing optimization/>
#    nohup bash orca-sp-CPCM.sh &
#
#  Output: CPCM/sp.out
###############################################################################

set -euo pipefail

# ── Resolution helpers ──────────────────────────────────────────────────

expand_path() {
  local p="$1"
  [[ "$p" == "~"* ]] && p="${HOME}${p:1}"
  echo "$p"
}

resolve_orca() {
  local candidate
  # 1. Explicit ORCA_BIN env var
  if [[ -n "${ORCA_BIN:-}" ]]; then
    candidate="$(expand_path "$ORCA_BIN")"
    [[ -x "$candidate" ]] && { echo "$candidate"; return 0; }
  fi
  # 2. Default ORCA_BIN from orca-opt.sh's convention
  candidate="/home/quantum/tools/orca_6_1_1_avx2/orca"
  [[ -x "$candidate" ]] && { echo "$candidate"; return 0; }
  # 3. Fallback: search tools/
  shopt -s nullglob
  for d in "$HOME/tools"/orca*; do
    candidate="$d/orca"
    [[ -x "$candidate" ]] && { echo "$candidate"; return 0; }
  done
  shopt -u nullglob
  # 4. System PATH
  candidate="$(type -P orca 2>/dev/null || true)"
  [[ -n "$candidate" && -x "$candidate" ]] && { echo "$candidate"; return 0; }
  return 1
}

# ── Discover optimization directory ─────────────────────────────────────

OPT_DIR="optimization"
if [[ ! -d "$OPT_DIR" ]]; then
  echo "[ERROR] No 'optimization/' directory found. Run from an orca-opt.sh output dir." >&2
  exit 1
fi

# ── Source theory from env file ─────────────────────────────────────────

ENV_FILE="$OPT_DIR/iqcap_orca.env"
if [[ ! -f "$ENV_FILE" ]]; then
  echo "[ERROR] iqcap_orca.env not found in $OPT_DIR/" >&2
  exit 1
fi

# Source the env file safely
# (It's auto-generated by iqcap-opt.sh with validated content)
IQCAP_ORCA_BASE=""
IQCAP_METHOD=""
source "$ENV_FILE" 2>/dev/null || true

if [[ -z "$IQCAP_ORCA_BASE" ]]; then
  echo "[ERROR] IQCAP_ORCA_BASE not set in $ENV_FILE" >&2
  exit 1
fi

echo "  Theory base: $IQCAP_ORCA_BASE"

# ── Discover charge / multiplicity from existing .inp ───────────────────

CHARGE=0
MULT=1

# Prefer sp.inp (TZVP single-point), fall back to opt.inp
INP_FILE=""
if [[ -f "$OPT_DIR/sp.inp" ]]; then
  INP_FILE="$OPT_DIR/sp.inp"
elif [[ -f "$OPT_DIR/opt.inp" ]]; then
  INP_FILE="$OPT_DIR/opt.inp"
else
  echo "[ERROR] Neither sp.inp nor opt.inp found in $OPT_DIR/" >&2
  exit 1
fi

# Extract charge/mult from the "* xyz <charge> <mult>" line
read_charge_mult() {
  local line
  line="$(grep -m1 '^\* *xyz' "$INP_FILE" 2>/dev/null || true)"
  if [[ -n "$line" ]]; then
    # Line format: "* xyz   0   1"
    read -r _ _ c m <<< "$line"
    CHARGE="${c:-0}"
    MULT="${m:-1}"
  fi
}
read_charge_mult

echo "  Charge: $CHARGE  Multiplicity: $MULT  (from $INP_FILE)"

# ── Geometry ────────────────────────────────────────────────────────────

XYZ_FILE="$OPT_DIR/opt.xyz"
if [[ ! -f "$XYZ_FILE" ]]; then
  echo "[ERROR] opt.xyz not found in $OPT_DIR/" >&2
  exit 1
fi

N_ATOMS=$(head -1 "$XYZ_FILE")
echo "  Atoms: $N_ATOMS  (from $XYZ_FILE)"

# ── ORCA binary ─────────────────────────────────────────────────────────

ORCA_EXE="$(resolve_orca)" || { echo "[ERROR] Cannot find ORCA executable" >&2; exit 1; }
echo "  ORCA: $ORCA_EXE"

# ── Resources ───────────────────────────────────────────────────────────

NPROCS="${NPROCS:-16}"
MAXCORE="${MAXCORE:-4096}"
echo "  nprocs: $NPROCS  maxcore: $MAXCORE MB"

# ── Create CPCM directory and input ─────────────────────────────────────

CPCM_DIR="CPCM"
mkdir -p "$CPCM_DIR"

# Build the ! line: base + tightSCF + CPCM(Water)
# IQCAP_ORCA_BASE already includes: PBE0 D3BJ def2-TZVP(-f) def2/J RIJCOSX
THEORY_LINE="$IQCAP_ORCA_BASE tightSCF CPCM(Water)"

# Write CPCM/sp.inp
cat > "$CPCM_DIR/sp.inp" <<EOF
! $THEORY_LINE
%maxcore  $MAXCORE
%pal nprocs   $NPROCS end
* xyz   $CHARGE   $MULT
$(awk 'NR>2 {print $0}' "$XYZ_FILE")
 *
EOF

echo "  Input written: $CPCM_DIR/sp.inp"

# ── Run ORCA ────────────────────────────────────────────────────────────

echo "  Running CPCM(Water) single-point..."
echo "  Start: $(date '+%Y-%m-%d %H:%M:%S')"
START_EPOCH=$(date +%s)

pushd "$CPCM_DIR" >/dev/null
"$ORCA_EXE" sp.inp > sp.out 2>&1
ORCA_EXIT=$?
popd >/dev/null

END_EPOCH=$(date +%s)
ELAPSED=$((END_EPOCH - START_EPOCH))

echo "  Done:  $(date '+%Y-%m-%d %H:%M:%S')  (${ELAPSED}s)"

# ── Check success ───────────────────────────────────────────────────────

if [[ $ORCA_EXIT -ne 0 ]]; then
  echo "[FAIL] ORCA exited with code $ORCA_EXIT" >&2
  exit 1
fi

if grep -q "ORCA TERMINATED NORMALLY" "$CPCM_DIR/sp.out"; then
  ENERGY=$(grep "FINAL SINGLE POINT ENERGY" "$CPCM_DIR/sp.out" | tail -1 | awk '{print $NF}')
  echo "  CPCM(Water) SCF energy: $ENERGY Hartree"
  echo ""
  echo "========================================"
  echo " CPCM single-point complete."
  echo " Output: $CPCM_DIR/sp.out"
  echo " Energy: $ENERGY Hartree"
  echo "========================================"
else
  echo "[FAIL] ORCA did NOT terminate normally. Check $CPCM_DIR/sp.out" >&2
  exit 1
fi
